version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: aisam-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: aisam_dev
    ports:
      - "5432:5432"
    volumes:
      - aisam_pgdata:/var/lib/postgresql/data

volumes:
  aisam_pgdata:
